spring:
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: none
  datasource:
    url: jdbc:mysql://localhost:3306/innova
    username: root
    password: Mule1379

logging.level.org.springframework.web: DEBUG
#security:
#  oauth2:
#    client:
#      clientId: 291135011638784
#      clientSecret: f7741450411ca209bac0670b6f29ba9b
#      accessTokenUri: https://graph.facebook.com/oauth/access_token
#      userAuthorizationUri: https://www.facebook.com/dialog/oauth
#      tokenName: oauth_token
#      authenticationScheme: query
#      clientAuthenticationScheme: form
#    resource:
#      userInfoUri: https://graph.facebook.com/me
